---
name: build

on:
  push:
    branches: [master]

  workflow_dispatch:
    inputs:
      pwm_tag:
        description: pwm/pwm repository tag
        required: true
        default: master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Replace '.' with '_' in tag
        run: |
          echo "::set-output name=PWM_TAG_UNDERSCORES::${PWM_TAG//./_}"
        env:
          PWM_TAG: ${{ github.event.inputs.pwm_tag }}
        id: transform_tag

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: ./alpine/
          platforms: linux/amd64,linux/arm64
          tags: devonm/pwm:${{ github.event.inputs.pwm_tag || env.DEFAULT_PWM_TAG }}
          push: ${{ github.event_name == 'workflow_dispatch' }}
          build-args: PWM_TAG=${{ steps.transform_tag.outputs.PWM_TAG_UNDERSCORES || env.DEFAULT_PWM_TAG }}
        env:
          DEFAULT_PWM_TAG: master
